import * as ctx from "./ExamContext";
import { ExamStateImpl } from "./ExamStateImpl";


export declare namespace ExamApi {
  export type LocaleCode = string;
  export type TranslatedText = string;
  export type Intl = Record<LocaleCode, TranslatedText>;

  export interface ErauSubject {
    id: string;
    tk?: string; // autogenerated
    title: Intl;
    questions: ErauQuestion[];
  }
  
  export interface ErauQuestion {
    id: string;
    tk?: string; // autogenerated 
    text: Intl;
    info: Intl[];
    answers: ErauAnswer[];
    qualifications: string[];
  }
  export interface ErauAnswer {
    id: string;
    tk?: string; // autogenerated
    value: Record<LocaleCode, {
      text: TranslatedText;
      isCorrect: boolean;
    }>; 
  }

  export interface Subject {
    tk: string;
    id: string;
    title: Intl;
    questions: Question[]
  }
  export interface Question {
    tk: string;
    id: string;
    subjectId: string;
    text: Intl;
    info: Intl[];
    answers: Answer[];
    correctAnswer: string | undefined;
    userAnswer: string | undefined;
    isAnsweredCorrectly: boolean | undefined;
    isAnswered: boolean;
  }
  export interface Answer {
    tk: string;
    questionId: string;
    subjectId: string;
    text: TranslatedText;
    correct: boolean;
    isAnswered: boolean;
    isQuestionAnswered: boolean  | undefined;
    isQuestionAnsweredCorrectly: boolean | undefined;
  }

  export interface Questionnaire {
    subjects: Record<string, Subject>; 
    questions: Record<string, Question>;
    answers: Record<string, Answer>;
  }

  export interface ExamState {
    selectSubject(subject: ErauSubject | undefined): ExamState;
    selectAnswer(answerTk: string): ExamState;
    suffle(nextNQuestions: number): ExamState;
    reset(): ExamState;
    all(): ExamState;


    source: ErauSubject[];
    questionnaire: Questionnaire;
    selectedSubject: ErauSubject | undefined;
    stats: { 
      perc: string;
      total: number;
      correct: number;
    }
  }

  export interface ExamContextType {
    value: ExamState;

    selectAnswer(answerTk: string): void;
    selectSubject(selectedSubject: ErauSubject | undefined): void;
    shuffle(nextNQuestions: number): void;
    reset(): void;
    all(): void;
  }
}

export namespace ExamApi {
  export const ExamProvider = ctx.ExamProvider;
  export const useExam = ctx.useExam;
  export const getInstance = (props: { source: ErauSubject[], locale: string, qualification: string }): ExamState => new ExamStateImpl(props);
}