spring:

server:
  address: 0.0.0.0

management:
  server:
    servlet.context-path: "/manage"
    add-application-context-header: false
  endpoints:
    web:
      exposure:
        include: "health,mappings"
 