export const en = {
  'document.title': 'ES1TP',
  'gamut.locale.et': 'Estonian',
  'gamut.locale.en': 'English',
  'gamut.buttons.serviceSelect': 'Select topic',
  'gamut.buttons.search': 'Search',
  'gamut.search.popover.title': 'Search',
  'gamut.search.popover.allLinks': 'All links',
  'gamut.search.popover.allPhones': 'All phone numbers',
  'gamut.search.popover.allForms': 'All exams',
  'gamut.search.popover.allServices': 'All subjects',
  'gamut.search.popover.input.placeholder': 'Search',
  'gamut.search.results.serviceLinks': 'Study material',
  'gamut.search.results.allResults': 'All results',
  'gamut.search.results.noResults': 'No results',
  'gamut.noValueIndicatorColon': ':',
  'footer.column2.title': 'Become a radio amateur!',
  'footer.column3.title': 'Links',
  'footer.column4.title': 'Contact',
  'footer.column2.become.amateur': 'How do I get started?',
  'footer.column3.link.erau': 'Estonian Amateur Radio League',
  'footer.column3.link.es1tp.qrz': 'QRZ ES1TP',
  'footer.column3.link.tpt': 'Tallinn Polytechnic School',
  'footer.column4.email': 'es1mw@erau.ee',
  'footer.column4.address1': 'Tallinn Polytechnic School',
  'footer.column4.address2': 'Pärnu mnt 57',
  'footer.column4.postalCode': '10135 Tallinn',
  'questionnaire.subject.select': 'Select exam subject',
  'questionnaire-results.title': 'Exam results: correct: {correct}/{total} Exam percentage: {perc}%',
  'questionnaire-header.all': 'All questions',
  'questionnaire-header.reset': 'Reset',
  'questionnaire-header.shuffle': 'Shuffle',
  'questionnaire-header.shuffle.big': 'Shuffle(25)',
  'buttons.scroll-to-top': 'Scroll to top',
  'buttons.cancel': 'Cancel'
}