export const et = {
  'document.title': 'ES1TP',
  'gamut.locale.et': 'Eesti keel',
  'gamut.locale.en': 'Inglise keel',
  'gamut.buttons.serviceSelect': 'Valige teema',
  'gamut.buttons.search': 'Otsing',
  'gamut.search.popover.title': 'Otsing',
  'gamut.search.popover.input.placeholder': 'Otsing',
  'gamut.search.results.serviceLinks': 'Õppematerjal',
  'gamut.search.results.allResults': 'Kõik tulemused',
  'gamut.search.results.noResults': 'Tulemusi pole',
  'gamut.noValueIndicatorColon': ':',
  'footer.column2.title': 'Hakka raadioamatööriks!',
  'footer.column3.title': 'Lingid',
  'footer.column4.title': 'Kontakti',
  'footer.column2.become.amateur': 'Kuidas saada raadioamatööriks?',
  'footer.column3.link.erau': 'Eesti Raadioamatööride Ühing',
  'footer.column3.link.es1tp.qrz': 'QRZ ES1TP',
  'footer.column3.link.tpt': 'Tallinna Polütehnikum',
  'footer.column4.email': 'es1mw@erau.ee',
  'footer.column4.address1': 'Tallinna Polütehnikum',
  'footer.column4.address2': 'Pärnu mnt 57',
  'footer.column4.postalCode': '10135 Tallinn'
}