export const et = {
  'document.title': 'ES1TP',
  'gamut.locale.et': 'Eesti keel',
  'gamut.locale.en': 'Inglise keel',
  'gamut.article.pagelinks.forms.title': 'Lingid',
  'gamut.buttons.serviceSelect': 'Valige teema',
  'gamut.buttons.search': 'Otsing',
  'gamut.search.popover.title': 'Otsing',
  'gamut.search.popover.allLinks': 'Kõik lingid',
  'gamut.search.popover.allPhones': 'Kõik telefoninumbrid',
  'gamut.search.popover.allForms': 'Kõik eksamid',
  'gamut.search.popover.allServices': 'Kõik ained',
  'gamut.search.popover.input.placeholder': 'Otsing',
  'gamut.search.results.serviceLinks': 'Õppematerjal',
  'gamut.search.results.allResults': 'Kõik tulemused',
  'gamut.search.results.noResults': 'Tulemusi pole',
  'gamut.noValueIndicatorColon': ':',
  'footer.column2.title': 'Hakka raadioamatööriks!',
  'footer.column3.title': 'Lingid',
  'footer.column4.title': 'Kontakti',
  'footer.column2.become.amateur': 'Kuidas saada raadioamatööriks?',
  'footer.column3.link.erau': 'Eesti Raadioamatööride Ühing',
  'footer.column3.link.es1tp.qrz': 'QRZ ES1TP',
  'footer.column3.link.tpt': 'Tallinna Polütehnikum',
  'footer.column4.email': 'es1mw@erau.ee',
  'footer.column4.address1': 'Tallinna Polütehnikum',
  'footer.column4.address2': 'Pärnu mnt 57',
  'footer.column4.postalCode': '10135 Tallinn',
  'events.none': 'Sündmust ei leitud',
  'events.filter': 'Filtreeri kuupäevavahemik',
  'events.today': 'Täna',
  'events.nextSevenDays': 'Järgmised 7 päeva',
  'events.nextFourteenDays': 'Järgmised 14 päeva',
  'events.nextThirtyDays': 'Järgmised 30 päeva',
  'questionnaire.subject.select': 'Valige eksami teema',
  'questionnaire-results.title': 'Eksamitulemused õige: {correct}/{total} Eksami protsent: {perc}%',
  'questionnaire-header.all': 'Kõik küsimused',
  'questionnaire-header.reset': 'Lähtestada',
  'questionnaire-header.shuffle': 'Juhuslikud(3)',
  'questionnaire-header.shuffle.big': 'Juhuslikud(25)',
  'buttons.scroll-to-top': 'Kerige üles',
  'buttons.cancel': 'Tühista'
}