export const fi = {
  'gamut.article.pagelinks.forms.title': 'Links',
  'gamut.search.popover.allLinks': 'All links',
  'footer.column2.title': 'Become a radio amateur!',
  'footer.column3.title': 'Links',
  'footer.column4.title': 'Contact',
  'footer.column2.become.amateur': 'How do I get started?',
  'footer.column3.link.erau': 'ERAU',
  'footer.column3.link.es1tp.qrz': 'QRZ ES1TP',
  'footer.column3.link.tpt': 'Tallinn Polytechnic School',
  'footer.column4.email': 'es1mw@erau.ee',
  'footer.column4.address1': 'Tallinn Polytechnic School',
  'footer.column4.address2': 'Pärnu mnt 57',
  'footer.column4.postalCode': '10135 Tallinn',
  'events.none': 'No events found',
  'events.filter': 'Filter date range',
  'events.today': 'Today',
  'events.nextSevenDays': 'Next 7 days',
  'events.nextFourteenDays': 'Next 14 days',
  'events.nextThirtyDays': 'Next 30 days',
  'questionnaire.subject.select': 'Select exam subject',
  'questionnaire-results.title': 'Exam results correct:{correct}/{total} Exam percentage: {perc}%',
  'questionnaire-header.all': 'All questions',
  'questionnaire-header.reset': 'Reset',
  'questionnaire-header.shuffle': 'Shuffle(3)',
  'questionnaire-header.shuffle.big': 'Shuffle(25)',
  'buttons.scroll-to-top': 'Scroll to top',
  'buttons.cancel': 'Cancel',
  'week': 'Viikko',
  'work_week': 'Työviikko',
  'day': 'Päivä',
  'month': 'Kuukausi',
  'previous': 'Edellinen',
  'next': 'Seuraava',
  'today': 'Tänään',
  'agenda': 'Agenda',
  'showMore': 'lisää'
}