export const fi = {
  'gamut.search.popover.allLinks': 'All links',
  'footer.column2.title': 'Become a radio amateur!',
  'footer.column3.title': 'Links',
  'footer.column4.title': 'Contact',
  'footer.column2.become.amateur': 'How do I get started?',
  'footer.column3.link.erau': 'ERAU',
  'footer.column3.link.es1tp.qrz': 'QRZ ES1TP',
  'footer.column3.link.tpt': 'Tallinn Polytechnic School',
  'footer.column4.email': 'es1mw@erau.ee',
  'footer.column4.address1': 'Tallinn Polytechnic School',
  'footer.column4.address2': 'Pärnu mnt 57',
  'footer.column4.postalCode': '10135 Tallinn',
  'questionnaire.subject.select': 'Select exam subject',
  'questionnaire-results.title': 'Exam results correct:{correct}/{total} Exam percentage: {perc}%',
  'questionnaire-header.all': 'All questions',
  'questionnaire-header.reset': 'Reset',
  'questionnaire-header.shuffle': 'Shuffle',
  'questionnaire-header.shuffle.big': 'Shuffle(25)',
  'button.scroll-to-top': 'Scroll to top'
}