export const fi = {
  'gamut.article.pagelinks.forms.title': 'Linkit',
  'gamut.search.popover.allLinks': 'Kaikki linkit',
  'footer.column2.title': 'Ryhdy radioamatööriksi!',
  'footer.column3.title': 'Linkit',
  'footer.column4.title': 'Yhteystiedot',
  'footer.column2.become.amateur': 'Miten pääsen alkuun?',
  'footer.column3.link.erau': 'ERAU',
  'footer.column3.link.es1tp.qrz': 'QRZ ES1TP',
  'footer.column3.link.tpt': 'Tallinnan Teknillinen Koulu',
  'footer.column4.email': 'es1mw@erau.ee',
  'footer.column4.address1': 'Tallinnan Teknillinen Koulu',
  'footer.column4.address2': 'Pärnu mnt 57',
  'footer.column4.postalCode': '10135 Tallinna',
  'events.none': 'Tapahtumia ei löytynyt',
  'events.filter': 'Suodata päivämääräväli',
  'events.today': 'Tänään',
  'events.nextSevenDays': 'Seuraavat 7 päivää',
  'events.nextFourteenDays': 'Seuraavat 14 päivää',
  'events.nextThirtyDays': 'Seuraavat 30 päivää',
  'questionnaire.subject.select': 'Valitse kokeen aihe',
  'questionnaire-results.title': 'Kokeen tulokset oikein:{correct}/{total} Kokeen prosentti: {perc}%',
  'questionnaire-header.all': 'Kaikki kysymykset',
  'questionnaire-header.reset': 'Nollaa',
  'questionnaire-header.shuffle': 'Sekoita(3)',
  'questionnaire-header.shuffle.big': 'Sekoita(25)',
  'buttons.scroll-to-top': 'Vieritä ylös',
  'buttons.cancel': 'Peruuta',
  'week': 'Viikko',
  'work_week': 'Työviikko',
  'day': 'Päivä',
  'month': 'Kuukausi',
  'previous': 'Edellinen',
  'next': 'Seuraava',
  'today': 'Tänään',
  'agenda': 'Agenda',
  'showMore': 'lisää'
}